### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by mohitsharma99**
# Application to the Class of 2020🎓

This pull request template helps you complete an application to the **Class of 2020**. Use the checklist below to verify you have followed the instructions correctly. 

## Checklist ✅

- [x] I have read the instructions on the README file before submitting my application. 
- [x] I made my submission by creating a folder on the `_data` folder and followed the naming convention mentioned in the instructions (`<username>`), added my profile picture and markdown file.
- [x] I have used the Markdown file template to add my information to the Year Book.
- [x] I have completed the form: `https://airtable.com/shrmuHxu38ZariKJi`
- [x] My application belongs to:
  - [x] **Tier 1** 📖: I added myself to the Year Book.
  - [ ] ~~**Tier 2** ✏️: I wrote a post on DEV about a project I built.~~
  - [ ] ~~**Tier 3** ✨: I want my project to be highlighted on stream.~~
- [x] I understand that a reviewer will merge my pull request after examining it or ask for changes in case needed.
- [x] I understand I should not tag or add a reviewer to this Pull Request.
- [x] I understand the photo added to the template will be used in the ceremony "Graduate Walk". 
- [x] I have [added the event](http://www.google.com/calendar/event?action=TEMPLATE&dates=20200615T160000Z%2F20200615T183000Z&text=%24%20git%20remote%20%3Cgraduation%3E%20%F0%9F%8E%93&location=https%3A%2F%2Fwww.twitch.tv%2Fgithubeducation&details=) to my Calendar.

### CODE REVIEW

**Comment by mohitsharma99** [comment]
review my profile

**Comment by Ahmeed2m** [comment]
@mohitsharma99 Thanks, your pull request now looks fine and ready for review, if you want to go further in the review process you must re-open the pull request.

**Comment by mohitsharma99** [comment]
> please make sure you correctly fill the form template and agree of all the terms also fill the form and check the form point.
> Make sure you have the check as the following [x] with now spaces inside the braces. Not [x ] or [ x] or [ x ]



> We have reviewed 📝 your application to the yearbook. It looks great ✨ but we found that some headers might be missing in the Markdown file or the format is broken (used any non-ascii characters?). I will close this PR so you can do the changes requested. You can open a new one once you've done the fixes and we will review it again.😊

Sir, I have not written a post on DEV so, I have not marked yet.

**Comment by elisemoe** [comment]
Hi @mohitsharma99 👋 this file needs to be updated to keep in the markdown headers and formatting: 

image

**Comment by mohitsharma99** [comment]
I filled al checks. Please confirm me again.

**Comment by mohitsharma99** [comment]
hey, What updates required?

**Pull request closed without merging**
