### PR TITLE
Yearbook Pull Request

### PR DESCRIPTION
**Pull request by benjaminlamont**
This pull request template helps you complete an application to the Class of 2020. Use the checklist below to verify you have followed the instructions correctly.

Checklist ✅

- [x] I have read the instructions on the README file before submitting my application.
- [x] I made my submission by creating a folder on the _data folder and followed the naming convention mentioned in the instructions (<username>), added my profile picture and markdown file.
- [x] I have used the Markdown file template to add my information to the Year Book.
- [x] I have completed the form: https://airtable.com/shrmuHxu38ZariKJi
My application belongs to:
- [x] Tier 1 📖: I added myself to the Year Book.
- [x] Tier 2 ✏️: I wrote a post on DEV about a project I built. [Here](https://dev.to/benjaminlamont/how-a-missing-feature-made-me-a-verified-discord-developer-387h)
- [x] Tier 3 ✨: I want my project to be highlighted on stream.
- [x] I understand that a reviewer will merge my pull request after examining it or ask for changes in case needed.
- [x] I understand I should not tag or add a reviewer to this Pull Request.
- [x] I understand the photo added to the template will be used in the ceremony "Graduate Walk".
- [x] I have added the event to my Calendar.

### CODE REVIEW

**Comment by darkRaspberry** [comment]
Dude where is ur checklist update it with these settings

Your checklist are incorrect. Edit ur changes. AND don't add ticks.

Just add the "x" (small x) between [] ( square bracket)
like this `[x]` not this [ x] or [x ] or [ ] x

only Correct way `[x]`

**Comment by benjaminlamont** [comment]
> Dude where is ur checklist update it with these settings
> 
> Your checklist are incorrect. Edit ur changes. AND don't add ticks.
> 
> Just add the "x" (small x) between [] ( square bracket)
> like this `[x]` not this [ x] or [x ] or [ ] x
> 
> only Correct way `[x]`

Oh gosh I just realised what you meant. Thanks for the heads up, for some reason I saw that pop up on the pull request and thought it was trying to replace the readme or something (idk it was late last night) and so I got rid of it. I'll fix it up as soon as I get a chance

**Comment by benjaminlamont** [comment]
> > Dude where is ur checklist update it with these settings
> > Your checklist are incorrect. Edit ur changes. AND don't add ticks.
> > Just add the "x" (small x) between [] ( square bracket)
> > like this `[x]` not this [ x] or [x ] or [ ] x
> > only Correct way `[x]`
> 
> Oh gosh I just realised what you meant. Thanks for the heads up, for some reason I saw that pop up on the pull request and thought it was trying to replace the readme or something (idk it was late last night) and so I got rid of it. I'll fix it up as soon as I get a chance

Fixed it now.

**Comment by darkRaspberry** [comment]
Dude you put space bet `[x]` This contain 3 character only without space it should change into this
`- [x] this` This whole things change in this
- [x] this

**Comment by benjaminlamont** [comment]
> Dude you put space bet `[x]` This contain 3 character only without space it should change into this
> `- [x] this` This whole things change in this
> 
> * [x]  this



> Dude you put space bet `[x]` This contain 3 character only without space it should change into this
> `- [x] this` This whole things change in this
> 
> * [x]  this

Yay, fixed it. Sorry, my bad.

**Pull request closed without merging**
