### PR TITLE
Please add me to yearbook

### PR DESCRIPTION
**Pull request by angelnator1998**
**CORRECTING ERRORS ON PR #1403 and PR #2433 **

Application to the Class of 2020🎓

This pull request template helps you complete an application to the Class of 2020. Use the checklist below to verify you have followed the instructions correctly.
Checklist ✅

[X] I have read the instructions on the README file before submitting my application.

I made my submission by creating a folder on the _data folder and followed the naming convention mentioned in the instructions (), added my profile picture and markdown file.
[X] I have used the Markdown file template to add my information to the Year Book.
[X] I have completed the form: https://airtable.com/shrmuHxu38ZariKJi
My application belongs to:

[X] Tier 1 📖: I added myself to the Year Book.
Tier 2 ✏️: I wrote a post on DEV about a project I built.
Tier 3 ✨: I want my project to be highlighted on stream.

[X] I understand that a reviewer will merge my pull request after examining it or ask for changes in case needed.
[X] I understand I should not tag or add a reviewer to this Pull Request.
[X] I understand the photo added to the template will be used in the ceremony "Graduate Walk".
[X] I have added the event to my Calendar.

### CODE REVIEW

**Comment by thejithinmathew** [comment]
Hi @angelnator1998 , I would request you to remove the space inside the checkbox.

**Comment by angelnator1998** [comment]
Hello @thejithinmathew like that ?

**Comment by thejithinmathew** [comment]
@angelnator1998 did you remove the X? The steps you followed must be marked.

**Comment by thejithinmathew** [comment]
> @angelnator1998 did you remove the X? The steps you followed must be marked.

NVM. I see you have used the emoji. You could also use [X] to denote the steps. It would be better.

**Comment by abhay-ranawat** [comment]
Your checklist are incorrect . Edit ur changes. AND don't add ticks.
Just add the "x" (small x) between [] ( square bracket)
like this [x] not this [ x] or [x ] or [ ] x

only Correct way [x]

https://help.github.com/en/github/managing-your-work-on-github/about-task-lists

**Pull request merged**
