### PR TITLE
Unable to get deleted files

### PR DESCRIPTION
**Pull request by blackjackal982**
# Application to the Class of 2020🎓

This pull request template helps you complete an application to the **Class of 2020**. Use the checklist below to verify you have followed the instructions correctly. 

## Checklist ✅

- [x] I have read the instructions on the README file before submitting my application. 
- [x] I made my submission by creating a folder on the `_data` folder and followed the naming convention mentioned in the instructions (`<username>`), added my profile picture and markdown file.
- [x] I have used the Markdown file template to add my information to the Year Book.
- [x] I understand that a reviewer will merge my pull request after examining it or ask for changes in case needed.
- [x] I understand I should not tag or add a reviewer to this Pull Request.
- [x] I understand the photo added to the template will be used in the ceremony "Graduate Walk". 
- [x] I have [added the event](http://www.google.com/calendar/event?action=TEMPLATE&dates=20200615T160000Z%2F20200615T183000Z&text=%24%20git%20remote%20%3Cgraduation%3E%20%F0%9F%8E%93&location=https%3A%2F%2Fwww.twitch.tv%2Fgithubeducation&details=) to my Calendar.

### CODE REVIEW

**Comment by blackjackal982** [comment]
Hi, I deleted the other files mistakenly which don't belong to me in the _data folder, hence it is showing as 8 files changed, I am unable to revert back changes to obtain the deleted files, I know I was supposed to change only 2 files of mine which I have done.

**Comment by blackjackal982** [comment]
Hi, removed the commented text from the markdown file.

**Comment by blackjackal982** [comment]
Removed double quotes as well

**Comment by blackjackal982** [comment]
@juanpflores  I deleted the the template files only as commented by @SulthanNK . I tried to revert back those deleted files, but seems like I permanently deleted those files on my local itself so unable to revert back changes.

**Comment by SulthanNK** [comment]
@blackjackal982 you need to create a new pull request without deleting any files and add your files to join in classroom as per instruction from @juanpflores

**Comment by blackjackal982** [comment]
Well in that case I have to delete this repo and fork the repo again

**Comment by SulthanNK** [comment]
> Well in that case I have to delete this repo and fork the repo again

Yes, just create a new PR as per requirement and ping me

**Pull request closed without merging**
