### PR TITLE
Adding napsternxg

### PR DESCRIPTION
**Pull request by napsternxg**
# Application to the Class of 2020🎓

This pull request template helps you complete an application to the **Class of 2020**. Use the checklist below to verify you have followed the instructions correctly. 

## Checklist ✅

- [x] I have read the instructions on the README file before submitting my application. 
- [x] I made my submission by creating a folder on the `_data` folder and followed the naming convention mentioned in the instructions (`<username>`), added my profile picture and markdown file.
- [x] I have used the Markdown file template to add my information to the Year Book.
- [x] I have completed the form: `https://airtable.com/shrmuHxu38ZariKJi`
- [x] My application belongs to:
  - [x] **Tier 1** 📖: I added myself to the Year Book.
  - [] ~~**Tier 2** ✏️: I wrote a post on DEV about a project I built.~~
  - [] ~~**Tier 3** ✨: I want my project to be highlighted on stream.~~
- [x] I understand that a reviewer will merge my pull request after examining it or ask for changes in case needed.
- [x] I understand I should not tag or add a reviewer to this Pull Request.
- [x] I understand the photo added to the template will be used in the ceremony "Graduate Walk". 
- [x] I have [added the event](http://www.google.com/calendar/event?action=TEMPLATE&dates=20200615T160000Z%2F20200615T183000Z&text=%24%20git%20remote%20%3Cgraduation%3E%20%F0%9F%8E%93&location=https%3A%2F%2Fwww.twitch.tv%2Fgithubeducation&details=) to my Calendar.

### CODE REVIEW

**Comment by napsternxg** [comment]
Done.

**Comment by CLiu13** [comment]
Thanks for the changes - however, you need to increase the size of your image so that it meets the dimension requirements (must be squared and **at least 544 x 544**. Current dimensions: 457 x 457).

**Comment by napsternxg** [comment]
Thanks, I have re-tried to update the image size.

**Comment by napsternxg** [comment]
Great. Let me know what need to be done to get the review approved.

**Comment by napsternxg** [comment]
@CLiu13 do let me know if I need to do anything else to merge it with master.

**Comment by CLiu13** [comment]
Everything seems to fine to me - a GitHub staff member will review your application sometime soon after checking it as well.

**Comment by napsternxg** [comment]
Thanks, will it have an issue, as the PR will be merged after the deadline?

**Comment by CLiu13** [comment]
As long as you submitted the swag request form prior to the deadline, I believe you should be all set - though I may be wrong.

**Comment by napsternxg** [comment]
Thanks.

**Comment by napsternxg** [comment]
Thanks @juanpflores

**Pull request merged**
