### PR TITLE
Old PR ref #4080

### PR DESCRIPTION
**Pull request by Pratibha-Goyal**
# Application to the Class of 2020🎓

This pull request template helps you complete an application to the **Class of 2020**. Use the checklist below to verify you have followed the instructions correctly. 

## Checklist ✅

- [x] I have read the instructions on the README file before submitting my application. 
- [x] I made my submission by creating a folder on the `_data` folder and followed the naming convention mentioned in the instructions (`<username>`), added my profile picture and markdown file.
- [x] I have used the Markdown file template to add my information to the Year Book.
- [x] I have completed the form: `https://airtable.com/shrmuHxu38ZariKJi`
- [x] My application belongs to:
  - [x] **Tier 1** 📖: I added myself to the Year Book.
  - [ ] ~~**Tier 2** ✏️: I wrote a post on DEV about a project I built.~~
  - [ ] ~~**Tier 3** ✨: I want my project to be highlighted on stream.~~
- [x] I understand that a reviewer will merge my pull request after examining it or ask for changes in case needed.
- [x] I understand I should not tag or add a reviewer to this Pull Request.
- [x] I understand the photo added to the template will be used in the ceremony "Graduate Walk". 
- [x] I have [added the event](http://www.google.com/calendar/event?action=TEMPLATE&dates=20200615T160000Z%2F20200615T183000Z&text=%24%20git%20remote%20%3Cgraduation%3E%20%F0%9F%8E%93&location=https%3A%2F%2Fwww.twitch.tv%2Fgithubeducation&details=) to my Calendar.

### CODE REVIEW

**Comment by SulthanNK** [comment]
Hey @Pratibha-Goyal 

That mentioned PR is already merged to master by @juanpflores 

So, May I know the reason for PR?

**Comment by Pratibha-Goyal** [comment]
I had to commit a revert changes request. Since, realized a hierarchy issue. Please review this one!

**Comment by ysfchn** [comment]
@SulthanNK Because files were in the wrong folder. So I commented in the old PR about reverting the changes.

@Pratibha-Goyal By the way, this PR doesn't contain a commit about deleting the old invalid files on the `_data` folder. Looks like you deleted the old files in your fork's `revert-4080-master` branch as expected but your PR targets for `grad` branch, not that one.

**Comment by SulthanNK** [comment]
@ysfchn  just now checked the master branch. She @Pratibha-Goyal directly put files into the _data folder without creating the folder by her name and it also merged to master branch now.

it only can delete by @juanpflores him.

**Comment by ysfchn** [comment]
@SulthanNK The pull requests can also contain commits that delete an existing file on the repo even the old one is merged. 😊

**Comment by juanpflores** [comment]
Nothing to worry about. This was fixed in #4336

**Pull request closed without merging**
