### PR TITLE
Updated the Changes for 2020

### PR DESCRIPTION
**Pull request by Ishaan28malik**
# Application to the Class of 2020🎓

This pull request template helps you complete an application to the **Class of 2020**. Use the checklist below to verify you have followed the instructions correctly. 

## Checklist ✅

- [x] I have read the instructions on the README file before submitting my application. 
- [x] I made my submission by creating a folder on the `_data` folder and followed the naming convention mentioned in the instructions (`<username>`), added my profile picture and markdown file.
- [x] I have used the Markdown file template to add my information to the Year Book.
- [x] I have completed the form: `https://airtable.com/shrmuHxu38ZariKJi`
- [x] My application belongs to:
  - [x] **Tier 1** 📖: I added myself to the Year Book.
  - [ ] ~~**Tier 2** ✏️: I wrote a post on DEV about a project I built.~~
  - [ ] ~~**Tier 3** ✨: I want my project to be highlighted on stream.~~
- [x] I understand that a reviewer will merge my pull request after examining it or ask for changes in case needed.
- [x] I understand I should not tag or add a reviewer to this Pull Request.
- [x] I understand the photo added to the template will be used in the ceremony "Graduate Walk". 
- [x] I have [added the event](http://www.google.com/calendar/event?action=TEMPLATE&dates=20200615T160000Z%2F20200615T183000Z&text=%24%20git%20remote%20%3Cgraduation%3E%20%F0%9F%8E%93&location=https%3A%2F%2Fwww.twitch.tv%2Fgithubeducation&details=) to my Calendar.

### CODE REVIEW

**Comment by Ishaan28malik** [comment]
@elisemoe I have updated the changes and made a new PR, please review and let me know any further changes are required.

**Comment by Ishaan28malik** [comment]
@juanpflores , @elisemoe Please check and update me, if anything is to be updated now.

**Comment by Ishaan28malik** [comment]
Please update for the same @juanpflores @elisemoe

**Comment by Abhishekds94** [comment]
I appreciate your follow up regarding the PR but one of the points in the checklist is not to tag any reviewers. Please do not repeat this in the coming days. All the PRs will be merged into the master accordingly and you would be notified about that soon.
I would suggest you to be patient.

Thank you!

**Comment by juanpflores** [comment]
We need you to open the pull request in order to review it.

**Comment by Ishaan28malik** [comment]
Their no option, I guess the rights are inactive. Need the right to re-open.I think I need to make the Repo clone and PR again in that case.

Selection_052

**Comment by Ishaan28malik** [comment]
SHould I make a New PR now ?

**Comment by juanpflores** [comment]
That would be the only way to add you to the yearbook.

**Comment by Ishaan28malik** [comment]
Alright let me make a new PR then, but the information submitted in the form will be accepted right, that was done previously since the form is unavailable now?

**Comment by Ishaan28malik** [comment]
I just made a new PR please review.

**Pull request closed without merging**
