### PR TITLE
followed the instructions

### PR DESCRIPTION
**Pull request by rgdeekshith**
# Application to the Class of 2020🎓

This pull request template helps you complete an application to the **Class of 2020**. Use the checklist below to verify you have followed the instructions correctly. 

## Checklist ✅

- [x] I have read the instructions on the README file before submitting my application. 
- [x] I made my submission by creating a folder on the `_data` folder and followed the naming convention mentioned in the instructions (`<username>`), added my profile picture and markdown file.
- [x] I have used the Markdown file template to add my information to the Year Book.
- [x] I have completed the form: `https://airtable.com/shrmuHxu38ZariKJi`
- [x] My application belongs to:
  - [x] **Tier 1** 📖: I added myself to the Year Book.
  - [x] **Tier 2** ✏️: I wrote a post on DEV about a project I built.
  - [x] **Tier 3** ✨: I want my project to be highlighted on stream.
- [x] I understand that a reviewer will merge my pull request after examining it or ask for changes in case needed.
- [x] I understand I should not tag or add a reviewer to this Pull Request.
- [x] I understand the photo added to the template will be used in the ceremony "Graduate Walk". 
- [x] I have [added the event](http://www.google.com/calendar/event?action=TEMPLATE&dates=20200615T160000Z%2F20200615T183000Z&text=%24%20git%20remote%20%3Cgraduation%3E%20%F0%9F%8E%93&location=https%3A%2F%2Fwww.twitch.tv%2Fgithubeducation&details=) to my Calendar.

### CODE REVIEW

**Comment by rgdeekshith** [comment]
> 
> 
> Your checklist are incorrect. Edit ur changes. AND don't add ticks.
> 
> Just add the "x" (small x) between [] ( square bracket)
> like this `[x]` not this [ x] or [x ] or [ ] x
> 
> only Correct way `[x]`

okay sir, thank you. Will do it now.

**Comment by rgdeekshith** [comment]
I don't know how to open the closed pull request and also don't know to edit the pull request, please help me or should I open a new pull request!

**Comment by rgdeekshith** [comment]
> We have reviewed memo your application to the yearbook. It looks great sparkles but we found that your profile picture doesn't have the minimum size. It should be at least 544x544 pixels but it is 400.0x400.0 px. I will close this PR so you can do the changes requested. You can open it again once you've done the fixes and we will review it again.blush

I don't know how to open a closed pull request and also I don't know how to make changes to a pull request! I tried searching in Google but haven't got correct answers, please help me in this task!

**Comment by juanpflores** [comment]
You can open a new pull request to do so

**Comment by rgdeekshith** [comment]
> You can open a new pull request to do so

Can't we change the existing, because I'm a beginner, it took me hours to make a single pull request because I'm new to GitHub. If there is a way please help me! I could make a pull request but it takes hours because of the fact that I'm new to GitHub and haven't had experience enough to work with request!

**Comment by juanpflores** [comment]
Done ✅

**Comment by rgdeekshith** [comment]
> You can open a new pull request to do so

Can't we change the existing, because I'm a beginner, it took me hours to make a single pull request because I'm new to GitHub. If there is a way please help me! I could make a pull request but it takes hours because of the fact that I'm new to GitHub and haven't had experience enough to work with request! 

> Done white_check_mark

Thank you sir, please tell me how to make changes now, please help me

**Comment by rgdeekshith** [comment]
> > You can open a new pull request to do so
> 
> Can't we change the existing, because I'm a beginner, it took me hours to make a single pull request because I'm new to GitHub. If there is a way please help me! I could make a pull request but it takes hours because of the fact that I'm new to GitHub and haven't had experience enough to work with request!
> 
> > Done white_check_mark
> 
> Thank you sir, please tell me how to make changes now, please help me

Sir, pull request merged means that I further need not have to do changes?

**Pull request merged**
