### PR TITLE
For joining the class of 2020

### PR DESCRIPTION
**Pull request by hrudesh-lenka**
# Application to the Class of 2020🎓

This pull request template helps you complete an application to the **Class of 2020**. Use the checklist below to verify you have followed the instructions correctly. 

## Checklist ✅

- [x] I have read the instructions on the README file before submitting my application. 
- [x] I made my submission by creating a folder on the `_data` folder and followed the naming convention mentioned in the instructions (`<username>`), added my profile picture and markdown file.
- [x] I have used the Markdown file template to add my information to the Year Book.
- [x] I have completed the form: `https://airtable.com/shrmuHxu38ZariKJi`
- [x] My application belongs to:
  - [x] **Tier 1** 📖: I added myself to the Year Book.
  - [ ] ~~**Tier 2** ✏️: I wrote a post on DEV about a project I built.~~
  - [ ] ~~**Tier 3** ✨: I want my project to be highlighted on stream.~~
- [x] I understand that a reviewer will merge my pull request after examining it or ask for changes in case needed.
- [x] I understand I should not tag or add a reviewer to this Pull Request.
- [x] I understand the photo added to the template will be used in the ceremony "Graduate Walk". 
- [x] I have [added the event](http://www.google.com/calendar/event?action=TEMPLATE&dates=20200615T160000Z%2F20200615T183000Z&text=%24%20git%20remote%20%3Cgraduation%3E%20%F0%9F%8E%93&location=https%3A%2F%2Fwww.twitch.tv%2Fgithubeducation&details=) to my Calendar.

### CODE REVIEW

**Comment by jely2002** [comment]
I believe this merge should be reverted, because the application has not been put inside the _data folder.

**Comment by hrudesh-lenka** [comment]
As per I remember I had followed the instructions correctly. What should I
do now ?

**Comment by hrudesh-lenka** [comment]
I ran git revert with id
 2 files changed, 7 deletions(-)
 delete mode 100644 hrudesh-lenka/hrudesh.md
 delete mode 100644 hrudesh-lenka/hrudesh.png
but the changes haven't reflected in repo. Did I do anything wrong ?

**Comment by mitulsavani** [comment]
Good catch @jely2002 👏 
@hrudesh-lenka don't worry about it, our great GitHub staff @elisemoe will fix the issue

**Comment by hrudesh-lenka** [comment]
Thanks for the assurance @mitulsavani.

**Pull request merged**
