### PR TITLE
IamVaibhavsar Added

### PR DESCRIPTION
**Pull request by IamVaibhavsar**
# Application to the Class of 2020🎓

This pull request template helps you complete an application to the **Class of 2020**. Use the checklist below to verify you have followed the instructions correctly. 

## Checklist ✅

- [x] I have read the instructions on the README file before submitting my application. 
- [x] I made my submission by creating a folder on the `_data` folder and followed the naming convention mentioned in the instructions (`<username>`), added my profile picture and markdown file.
- [x] I have used the Markdown file template to add my information to the Year Book.
- [x] I understand that a reviewer will merge my pull request after examining it or ask for changes in case needed.
- [x] I understand I should not tag or add a reviewer to this Pull Request.
- [x] I understand the photo added to the template will be used in the ceremony "Graduate Walk". 
- [x] I have [added the event](http://www.google.com/calendar/event?action=TEMPLATE&dates=20200615T160000Z%2F20200615T183000Z&text=%24%20git%20remote%20%3Cgraduation%3E%20%F0%9F%8E%93&location=https%3A%2F%2Fwww.twitch.tv%2Fgithubeducation&details=) to my Calendar.

### CODE REVIEW

**Comment by IamVaibhavsar** [comment]
I have added a square image of a 1:1 ratio which has a resolution of 1800 x 1800 px and changed the file name in the markdown file accordingly.

**Comment by IamVaibhavsar** [comment]
Thank You for merging the pull request.
What kind of goodies, we are going to get virtually?

When we will get them?

Thank You|


*Thanks & Regards,*
*Vaibhav Bhavsar*
B.E. 3rd Year,
Computer Engineering,
KKWIEER, Nashik

**Comment by IamVaibhavsar** [comment]
Hii everyone,
when my Pull request will get merged?
or do I need to close the PR.

please reply and support.
Thanks in advance!

**Comment by mitulsavani** [comment]
Your PR will be merged soon by one of the staff members who have the *write* access. You will receive an email once the PR is merged. 
Meanwhile, sit back and enjoy the weekend :)

**Comment by IamVaibhavsar** [comment]
Thank You Mitul ! Same to you!

**Comment by IamVaibhavsar** [comment]
what are the social media handles?

**Comment by IamVaibhavsar** [comment]
@juanpflores @mitulsavani How you are distributing the swags?
are they digital or you are shipping them offline in these situations?
also, let me know about the GitHub education social media handles where you post the updates about the same.

Thank you in advance!

**Pull request merged**
