### PR TITLE
add Utkarsh

### PR DESCRIPTION
**Pull request by UtkarshChaurasia**
# Application to the Class of 2020🎓

This pull request template helps you complete an application to the **Class of 2020**. Use the checklist below to verify you have followed the instructions correctly. 

## Checklist ✅

- [x] I have read the instructions on the README file before submitting my application. 
- [x] I made my submission by creating a folder on the `_data` folder and followed the naming convention mentioned in the instructions (`<username>`), added my profile picture and markdown file.
- [x] I have used the Markdown file template to add my information to the Year Book.
- [x] I have completed the form: `https://airtable.com/shrmuHxu38ZariKJi`
- [x] My application belongs to:
  - [x] **Tier 1** 📖: I added myself to the Year Book.
  - [x] **Tier 2** ✏️: I wrote a post on DEV about a project I built.
  - [ ] ~~**Tier 3** ✨: I want my project to be highlighted on stream.~~
- [x] I understand that a reviewer will merge my pull request after examining it or ask for changes in case needed.
- [x] I understand I should not tag or add a reviewer to this Pull Request.
- [x] I understand the photo added to the template will be used in the ceremony "Graduate Walk". 
- [x] I have [added the event](http://www.google.com/calendar/event?action=TEMPLATE&dates=20200615T160000Z%2F20200615T183000Z&text=%24%20git%20remote%20%3Cgraduation%3E%20%F0%9F%8E%93&location=https%3A%2F%2Fwww.twitch.tv%2Fgithubeducation&details=) to my Calendar.

### CODE REVIEW

**Comment by UtkarshChaurasia** [comment]
@Mohammed-Shoaib I think they have closed tier 2 and tier 3 swag registration that's why strikethrough sign is mentioned

**Comment by Mohammed-Shoaib** [comment]
Based on [this](https://github.com/education/graduation/issues/2314#issuecomment-633104268) comment from one of the maintainers

> Pull requests and shipping information submitted before 2:30 PM PDT on 5/22 are still eligible for Tier 2.

Since your original pull request satisfies this condition, you qualify for the swags!

**Comment by UtkarshChaurasia** [comment]
@juanpflores so what to do next? Any changes required?

**Comment by Mohammed-Shoaib** [comment]
No, it just means your pull request is correct. :sparkles:

Now sit back, relax, and wait for it to get merged! :rocket:

**Pull request merged**
