### PR TITLE
New PR, added --- at the beginning and the end of this file

### PR DESCRIPTION
**Pull request by Puja7629**
# Application to the Class of 2020🎓

This pull request template helps you complete an application to the **Class of 2020**. Use the checklist below to verify you have followed the instructions correctly. 

## Checklist ✅

- [x] I have read the instructions on the README file before submitting my application. 
- [x] I made my submission by creating a folder on the `_data` folder and followed the naming convention mentioned in the instructions (`<username>`), added my profile picture and markdown file.
- [x] I have used the Markdown file template to add my information to the Year Book.
- [x] I understand that a reviewer will merge my pull request after examining it or ask for changes in case needed.
- [x] I understand I should not tag or add a reviewer to this Pull Request.
- [x] I understand the photo added to the template will be used in the ceremony "Graduate Walk". 
- [x] I have [added the event](http://www.google.com/calendar/event?action=TEMPLATE&dates=20200615T160000Z%2F20200615T183000Z&text=%24%20git%20remote%20%3Cgraduation%3E%20%F0%9F%8E%93&location=https%3A%2F%2Fwww.twitch.tv%2Fgithubeducation&details=) to my Calendar.

### CODE REVIEW

**Comment by Puja7629** [comment]
Kindly review my PR. I have added --- at the beginning and the end of this file.

**Comment by Puja7629** [comment]
Should I fill the shipment form again? I have created a new PR. but the shipment form link is not valid now.

**Comment by Puja7629** [comment]
Hi, @sarnava1 Thanks a lot for reviewing.
can you please let me know should I fill the shipment form again? I have created a new PR. but the shipment form link is not valid now.

**Comment by y-martinez** [comment]
Hi @Puja7629, please check out the updates in the readme file, If you created the PR before May 26, 12:00 AM PDT, yes you had to fill out the form, but since that day no more responses are accepted, it was indicated that people could continue doing PR but these would not apply to Tier 1, which were the swag.

**Comment by Puja7629** [comment]
@y-martinez Hey! I have submitted my first PR before 26th and also filled the form before 26th May. I asked that the second PR which I have created today so do I need to fill the form again for the new PR? As the link of new PR has changed right? I hope my question is clear to you :)


My PR got reviewed today but didn't get merged. Why?

**Comment by y-martinez** [comment]
Ohhh I get it, sorry @Puja7629 I didn't see that you PR was created before May 26, I see that you did an update to that PR, is that correct?

Regarding the reason why it has not been merge, apparently it is because they are merging in order of creation, but the most important thing is, the text that appears in the readme file said this:

> We’ll continue to review and get everyone merged before the event on June 15th

**Comment by Puja7629** [comment]
> Ohhh I get it, sorry @Puja7629 I didn't see that you PR was created before May 26, I see that you did an update to that PR, is that correct?
> 
> Regarding the reason why it has not been merge, apparently it is because they are merging in order of creation, but the most important thing is, the text that appears in the readme file said this:
> 
> > We’ll continue to review and get everyone merged before the event on June 15th

**Comment by Puja7629** [comment]
Thak you @y-martinez

**Comment by Puja7629** [comment]
@y-martinez By mistake, I closed this PR but I reopened it. I hope no issue will be arsing because of my silly mistake? Can you please answer?

**Comment by Puja7629** [comment]
Thank you so much @juanpflores :)

**Pull request merged**
