### PR TITLE
added saim folder 5/20/2020 5:06 AM

### PR DESCRIPTION
**Pull request by saimmehmood**
# Application to the Class of 2020🎓

This pull request template helps you complete an application to the **Class of 2020**. Use the checklist below to verify you have followed the instructions correctly. 

## Checklist ✅

- [ ] I have read the instructions on the README file before submitting my application. 
- [ ] I made my submission by creating a folder on the `_data` folder and followed the naming convention mentioned in the instructions (`<username>`), added my profile picture and markdown file.
- [ ] I have used the Markdown file template to add my information to the Year Book.
- [ ] I have completed the form: `https://airtable.com/shrmuHxu38ZariKJi`
- [ ] My application belongs to:
  - [ ] **Tier 1** 📖: I added myself to the Year Book.
  - [ ] **Tier 2** ✏️: I wrote a post on DEV about a project I built.
  - [ ] **Tier 3** ✨: I want my project to be highlighted on stream.
- [ ] I understand that a reviewer will merge my pull request after examining it or ask for changes in case needed.
- [ ] I understand I should not tag or add a reviewer to this Pull Request.
- [ ] I understand the photo added to the template will be used in the ceremony "Graduate Walk". 
- [ ] I have [added the event](http://www.google.com/calendar/event?action=TEMPLATE&dates=20200615T160000Z%2F20200615T183000Z&text=%24%20git%20remote%20%3Cgraduation%3E%20%F0%9F%8E%93&location=https%3A%2F%2Fwww.twitch.tv%2Fgithubeducation&details=) to my Calendar.

### CODE REVIEW

**Comment by saimmehmood** [comment]
checklist correctly updated.

**Comment by darkRaspberry** [comment]
You have updated the check list in directory Not here. I mean here. I _data folder need only 2 files.

**Comment by saimmehmood** [comment]
To be honest, I can't seem to understand.
Anyhow, I have deleted other files from the _data folder.

**Comment by saimmehmood** [comment]
already done that mate!

**Comment by darkRaspberry** [comment]
I am afraid. Your pull request contain 11 files and empty checklist(you filled during creating this pull request)

**Comment by saimmehmood** [comment]
Apologies, I have deleted other files from _data folder. There is only my folder there with a picture and .md file. And I have also filled the checklist with x's. 
Have a look:
https://github.com/saimmehmood/graduation

**Comment by darkRaspberry** [comment]
you are not understanding.
you have to edit the checklist( You first comment in this PR. the top above comment. this one https://github.com/education/graduation/pull/620#issue-420614411 ).
Also
your PR should only edit 2 files inv_data folder. you don't have to delete other's files.
restore everything in the PR.
**And just update 2 files in `-data/<username>` folder with your <username>.md and profile picture**

if u still don't understand tell me.

**Pull request closed without merging**
