### PR TITLE
All GOOD

### PR DESCRIPTION
**Pull request by poshan0126**
# Application to the Class of 2020🎓

This pull request template helps you complete an application to the **Class of 2020**. Use the checklist below to verify you have followed the instructions correctly. 

## Checklist ✅

- [Yes ] I have read the instructions on the README file before submitting my application. 
- [Yes  ] I made my submission by creating a folder on the `_data` folder and followed the naming convention mentioned in the instructions (`<username>`), added my profile picture and markdown file.
- [Yes  ] I have used the Markdown file template to add my information to the Year Book.
- [Yes  ] I have completed the form: `https://airtable.com/shrmuHxu38ZariKJi`
- [Yes  ] My application belongs to:
  - [ Yes ] **Tier 1** 📖: I added myself to the Year Book.
  - [ No] ~~**Tier 2** ✏️: I wrote a post on DEV about a project I built.~~
  - [No ] ~~**Tier 3** ✨: I want my project to be highlighted on stream.~~
- [ Yes ] I understand that a reviewer will merge my pull request after examining it or ask for changes in case needed.
- [Yes  ] I understand I should not tag or add a reviewer to this Pull Request.
- [Yes  ] I understand the photo added to the template will be used in the ceremony "Graduate Walk". 
- [Yes  ] I have [added the event](http://www.google.com/calendar/event?action=TEMPLATE&dates=20200615T160000Z%2F20200615T183000Z&text=%24%20git%20remote%20%3Cgraduation%3E%20%F0%9F%8E%93&location=https%3A%2F%2Fwww.twitch.tv%2Fgithubeducation&details=) to my Calendar.

### CODE REVIEW

**Comment by poshan0126** [comment]
Done sir!

**Comment by Mohammed-Shoaib** [comment]
Hey, you closed this one and opened a new PR #4003, it has been reviewed.
Thank you @saarques :relaxed:

**Comment by saarques** [comment]
> Hey, you closed this one and opened a new PR #4003, it has been reviewed.
> Thank you @saarques relaxed

Cool, but there still is a conflict. :/

**Comment by poshan0126** [comment]
What is the conflict now?

**Comment by Mohammed-Shoaib** [comment]
You already pushed an image previously in PR #3978 which can be found [here](https://github.com/education/graduation/blob/master/_data/poshan0126/poshan.jpg). So you will need to delete the new image from #4003.

**Pull request closed without merging**
