### PR TITLE
Add realicejoanne to the entry

### PR DESCRIPTION
**Pull request by realicejoanne**
# Application to the Class of 2020🎓

This pull request template helps you complete an application to the **Class of 2020**. Use the checklist below to verify you have followed the instructions correctly. 

## Checklist ✅

- [x] I have read the instructions on the README file before submitting my application. 
- [x] I made my submission by creating a folder on the `_data` folder and followed the naming convention mentioned in the instructions (`<username>`), added my profile picture and markdown file.
- [x] I have used the Markdown file template to add my information to the Year Book.
- [x] I have completed the form: `https://airtable.com/shrmuHxu38ZariKJi`
- [x] My application belongs to:
  - [x] **Tier 1** 📖: I added myself to the Year Book.
  - [ ] ~~**Tier 2** ✏️: I wrote a post on DEV about a project I built.~~
  - [ ] ~~**Tier 3** ✨: I want my project to be highlighted on stream.~~
- [x] I understand that a reviewer will merge my pull request after examining it or ask for changes in case needed.
- [x] I understand I should not tag or add a reviewer to this Pull Request.
- [x] I understand the photo added to the template will be used in the ceremony "Graduate Walk". 
- [x] I have [added the event](http://www.google.com/calendar/event?action=TEMPLATE&dates=20200615T160000Z%2F20200615T183000Z&text=%24%20git%20remote%20%3Cgraduation%3E%20%F0%9F%8E%93&location=https%3A%2F%2Fwww.twitch.tv%2Fgithubeducation&details=) to my Calendar.

### CODE REVIEW

**Comment by saarques** [comment]
Hey @realicejoanne Can you please remove the extra files from the PR? That would make it easy for the team.

**Comment by realicejoanne** [comment]
Hi @saarques @elisemoe thank you for reviewing my application to the yearbook. I'm sorry, I just want to fix this issue (https://github.com/education/graduation/issues/3639). Glad to see that's already fixed. I will fix this right now.

**Comment by saarques** [comment]
> Hi @saarques @elisemoe thank you for reviewing my application to the yearbook. I'm sorry, I just want to fix this issue (#3639). Glad to see that's already fixed. I will fix this right now.

Cool, @realicejoanne  Create a new PR and comment here, I will review it right away.

**Comment by realicejoanne** [comment]
@saarques I already mentioned the revised PR above. Please review it. Thanks a lot!

**Pull request closed without merging**
