### PR TITLE
Added myself

### PR DESCRIPTION
**Pull request by rusucosmin**
Application to the Class of 2020🎓
This pull request template helps you complete an application to the Class of 2020. Use the checklist below to verify you have followed the instructions correctly.

Checklist ✅

- [x] I have read the instructions on the README file before submitting my application.

- [x]  I made my submission by creating a folder on the _data folder and followed the naming convention mentioned in the instructions (<username>), added my profile picture and markdown file.

- [x] I have used the Markdown file template to add my information to the Year Book.

- [x] I have completed the form: https://airtable.com/shrmuHxu38ZariKJi
My application belongs to:
   Tier 1 📖: I added myself to the Year Book.

- [x] I understand that a reviewer will merge my pull request after examining it or ask for changes in case needed.

- [x] I understand I should not tag or add a reviewer to this Pull Request.

- [x] I understand the photo added to the template will be used in the ceremony "Graduate Walk".

- [x] I have added the event to my Calendar.

### CODE REVIEW

**Comment by rusucosmin** [comment]
@darkRaspberry fixed, thanks!

**Comment by darkRaspberry** [comment]
You have done wrong see other people PR This [x] should change in a tick box

`- [x] This works.` See is your checkbox is seems like this code.
This should change in 
- [x] This should be works

**Comment by rusucosmin** [comment]
Okay, let's see if this is the one

**Comment by darkRaspberry** [comment]
Just OK.
IT will work.
Wait till merged

**Pull request merged**
