### PR TITLE
Joining class of 2020 - Alok Bharti

### PR DESCRIPTION
**Pull request by alokbharti**
# Application to the Class of 2020🎓

This pull request template helps you complete an application to the **Class of 2020**. Use the checklist below to verify you have followed the instructions correctly. 

## Checklist ✅

- [x] I have read the instructions on the README file before submitting my application. 
- [x] I made my submission by creating a folder on the `_data` folder and followed the naming convention mentioned in the instructions (`<username>`), added my profile picture and markdown file.
- [x] I have used the Markdown file template to add my information to the Year Book.
- [x] I have completed the form: `https://airtable.com/shrmuHxu38ZariKJi`
- [x] My application belongs to:
  - [x] **Tier 1** 📖: I added myself to the Year Book.
  - [x] ~~**Tier 2** ✏️: I wrote a post on DEV about a project I built.~~
  - [x] ~~**Tier 3** ✨: I want my project to be highlighted on stream.~~
- [x] I understand that a reviewer will merge my pull request after examining it or ask for changes in case needed.
- [x] I understand I should not tag or add a reviewer to this Pull Request.
- [x] I understand the photo added to the template will be used in the ceremony "Graduate Walk". 
- [x] I have [added the event](http://www.google.com/calendar/event?action=TEMPLATE&dates=20200615T160000Z%2F20200615T183000Z&text=%24%20git%20remote%20%3Cgraduation%3E%20%F0%9F%8E%93&location=https%3A%2F%2Fwww.twitch.tv%2Fgithubeducation&details=) to my Calendar.

### CODE REVIEW

**Comment by alokbharti** [comment]
> 1. Image is in wrong dimensions. As per the requirement
> 
> > Accepted files are png and jpg, should be squared and minimum size 544x544 pixels
> 
> 1. Wrong formatting in the markdown file. `"` is not allowed.
> 
> > avoid using quotes(") to guarantee the format remains the same.

Image is of 582x583 and is in square shape.

**Comment by ShaunLWM** [comment]
1. Image must be squared in a sense that the width and height must the same. 582x583 is not squared.

2. Your quote consist of ```"```.
> quote: "CODE till you're addicted to it!!"

Remove it so it becomes
> quote: CODE till you're addicted to it!!

**Comment by alokbharti** [comment]
@ShaunLWM I've updated my files, please have a look

**Comment by ShaunLWM** [comment]
Yup, looks good to me. Now just have to wait for them to approve this commit :)

**Comment by alokbharti** [comment]
Thanks 🤩

**Pull request merged**
