### PR TITLE
MyDataForClassOf2020

### PR DESCRIPTION
**Pull request by faizan8684**
# Application to the Class of 2020🎓

This pull request template helps you complete an application to the **Class of 2020**. Use the checklist below to verify you have followed the instructions correctly. 

## Checklist ✅

- [x] I have read the instructions on the README file before submitting my application. 
- [x] I made my submission by creating a folder on the `_data` folder and followed the naming convention mentioned in the instructions (`<username>`), added my profile picture and markdown file.
- [x] I have used the Markdown file template to add my information to the Year Book.
- [x] I understand that a reviewer will merge my pull request after examining it or ask for changes in case needed.
- [x] I understand I should not tag or add a reviewer to this Pull Request.
- [x] I understand the photo added to the template will be used in the ceremony "Graduate Walk". 
- [x] I have [added the event](http://www.google.com/calendar/event?action=TEMPLATE&dates=20200615T160000Z%2F20200615T183000Z&text=%24%20git%20remote%20%3Cgraduation%3E%20%F0%9F%8E%93&location=https%3A%2F%2Fwww.twitch.tv%2Fgithubeducation&details=) to my Calendar.

### CODE REVIEW

**Comment by faizan8684** [comment]
I have updated the name of image file, please review it.

**Comment by faizan8684** [comment]
@Mohammed-Shoaib 
I tried making it square, but when I saved it, the dimensions got changed again, any fix?

**Comment by Mohammed-Shoaib** [comment]
@faizan8684 That's weird :confused:. I've cropped out a square section from your image making it exactly **544x544** pixels :white_square_button:.

faizan

You'll still have to upload the file yourself in the PR as I do not have _write_ access :writing_hand:.

**Comment by faizan8684** [comment]
I have uploaded my image from my end! Please check if it's correct or not?
This is the different image from yours.

**Comment by faizan8684** [comment]
I guess yours is better I will upload that 😄

**Comment by faizan8684** [comment]
I have uploaded yours, Thanks! :)

**Comment by Mohammed-Shoaib** [comment]
@faizan8684 Just checked, your previous image is also **perfect**. So you can use whichever you'd like! :100:
* [previous image](https://raw.githubusercontent.com/education/graduation/2db990876c0d7f5576e79192ac840e712f480be0/_data/faizan8684/faizan.jpg)
* [current image](https://raw.githubusercontent.com/education/graduation/3e4b16781e4665b1592b4d240341cf2ac927928b/_data/faizan8684/faizan.jpg)

**Comment by faizan8684** [comment]
> @faizan8684 Just checked, your previous image is also **perfect**. So you can use whichever you'd like! :100:
> * [previous image](https://raw.githubusercontent.com/education/graduation/2db990876c0d7f5576e79192ac840e712f480be0/_data/faizan8684/faizan.jpg)
> * [current image](https://raw.githubusercontent.com/education/graduation/3e4b16781e4665b1592b4d240341cf2ac927928b/_data/faizan8684/faizan.jpg)

@Mohammed-Shoaib
Yep, I think it's everything is fine now.

**Pull request merged**
