### PR TITLE
Please add me also

### PR DESCRIPTION
**Pull request by IqraHashmi**
# Application to the Class of 2020🎓

This pull request template helps you complete an application to the **Class of 2020**. Use the checklist below to verify you have followed the instructions correctly. 

## Checklist ✅

- [x] I have read the instructions on the README file before submitting my application. 
- [x] I made my submission by creating a folder on the `_data` folder and followed the naming convention mentioned in the instructions (`<username>`), added my profile picture and markdown file.
- [x] I have used the Markdown file template to add my information to the Year Book.
- [x] I understand that a reviewer will merge my pull request after examining it or ask for changes in case needed.
- [x] I understand I should not tag or add a reviewer to this Pull Request.
- [x] I understand the photo added to the template will be used in the ceremony "Graduate Walk". 
- [x] I have [added the event](http://www.google.com/calendar/event?action=TEMPLATE&dates=20200615T160000Z%2F20200615T183000Z&text=%24%20git%20remote%20%3Cgraduation%3E%20%F0%9F%8E%93&location=https%3A%2F%2Fwww.twitch.tv%2Fgithubeducation&details=) to my Calendar.

### CODE REVIEW

**Review by chayan-chawra — CHANGES_REQUESTED** [review]
Hi @IqraHashmi 
Your checklist is not complete.
please put a 'x' between []. Please ensure there is no space between the brackets.
[x] this is the correct way of doing it.

Also please change your image name to your github profile name. Also update your image name in the .md file.

Please make the above changes and then I will review your PR again 😃

**Comment by IqraHashmi** [comment]
I have updated the files.Please review it.Thank you

**Review by chayan-chawra — CHANGES_REQUESTED** [review]
Hi @IqraHashmi 
You need to change the name of your .md file as well as your folder name to your Github username.

Make the above change and I will review your PR again 😃

**Review by chayan-chawra — APPROVED** [review]
Hi @IqraHashmi 
1. Your checklist is complete.
2. Your image dimensions are correct.
3. Your file names are correct.

Congratulations on graduating 🎉

**Pull request closed without merging**
