### PR TITLE
Graduation Year 2020

### PR DESCRIPTION
**Pull request by surajsahani**
# Application to the Class of 2020🎓

This pull request template helps you complete an application to the **Class of 2020**. Use the checklist below to verify you have followed the instructions correctly. 

## Checklist ✅

- [x] I have read the instructions on the README file before submitting my application. 
- [x] I made my submission by creating a folder on the `_data` folder and followed the naming convention mentioned in the instructions (`<username>`), added my profile picture and markdown file.
- [x] I have used the Markdown file template to add my information to the Year Book.
- [x] I have completed the form: `https://airtable.com/shrmuHxu38ZariKJi`
- [x] My application belongs to:
  - [x] **Tier 1** 📖: I added myself to the Year Book.
  - [x] **Tier 2** ✏️: I wrote a post on DEV about a project I built.
  - [x] **Tier 3** ✨: I want my project to be highlighted on stream.
- [x] I understand that a reviewer will merge my pull request after examining it or ask for changes in case needed.
- [x] I understand I should not tag or add a reviewer to this Pull Request.
- [x] I understand the photo added to the template will be used in the ceremony "Graduate Walk". 
- [x] I have [added the event](http://www.google.com/calendar/event?action=TEMPLATE&dates=20200615T160000Z%2F20200615T183000Z&text=%24%20git%20remote%20%3Cgraduation%3E%20%F0%9F%8E%93&location=https%3A%2F%2Fwww.twitch.tv%2Fgithubeducation&details=) to my Calendar.

### CODE REVIEW

**Comment by surajsahani** [comment]
# # @jeffrafter  can you review the code?

**Comment by surajsahani** [comment]
new checkbox clicked

**Comment by surajsahani** [comment]
Edited the name changes

**Comment by saarques** [comment]
Hey @surajsahani Can you please remove that extra file please!

**Comment by surajsahani** [comment]
> Hey @surajsahani Can you please remove that extra file please! Is it needed?

Hi @saarques thank you for helping Should I remove .github/workflows/blank.yml file?

**Comment by saarques** [comment]
> > Hey @surajsahani Can you please remove that extra file please! Is it needed?
> 
> Hi @saarques thank you for helping Should I remove .github/workflows/blank.yml file?

Yep, only two files should be modified!

**Comment by surajsahani** [comment]
> > > Hey @surajsahani Can you please remove that extra file please! Is it needed?
> > 
> > 
> > Hi @saarques thank you for helping Should I remove .github/workflows/blank.yml file?
> 
> Yep, only two files should be modified!

I am not sure how to remove .yml files from my PR. any help please?

**Comment by saarques** [comment]
Please go to the files changed section and see if you can delete the file from there, otherwise leave it like that, the team will see what they need to do. :)

**Comment by surajsahani** [comment]
> Please go to the files changed section and see if you can delete the file from there, otherwise leave it like that, the team will see what they need to do. :)

Thank a lot.

**Pull request closed without merging**
