### PR TITLE
This is my  pull rquest for education 2020

### PR DESCRIPTION
**Pull request by AkhilGKrishnan**
# Application to the Class of 2020🎓

This pull request template helps you complete an application to the **Class of 2020**. Use the checklist below to verify you have followed the instructions correctly. 

## Checklist ✅

- [x] I have read the instructions on the README file before submitting my application. 
- [x] I made my submission by creating a folder on the `_data` folder and followed the naming convention mentioned in the instructions (`<username>`), added my profile picture and markdown file.
- [x] I have used the Markdown file template to add my information to the Year Book.
- [x] I have completed the form: `https://airtable.com/shrmuHxu38ZariKJi`
- [x] My application belongs to:
  - [x] **Tier 1** 📖: I added myself to the Year Book.
  - [x] **Tier 2** ✏️: I wrote a post on DEV about a project I built.
  - [x] **Tier 3** ✨: I want my project to be highlighted on stream.
- [x] I understand that a reviewer will merge my pull request after examining it or ask for changes in case needed.
- [x] I understand I should not tag or add a reviewer to this Pull Request.
- [x] I understand the photo added to the template will be used in the ceremony "Graduate Walk". 
- [x] I have [added the event](http://www.google.com/calendar/event?action=TEMPLATE&dates=20200615T160000Z%2F20200615T183000Z&text=%24%20git%20remote%20%3Cgraduation%3E%20%F0%9F%8E%93&location=https%3A%2F%2Fwww.twitch.tv%2Fgithubeducation&details=) to my Calendar.

### CODE REVIEW

**Comment by AkhilGKrishnan** [comment]
I chaged my mistakes

**Comment by AkhilGKrishnan** [comment]
I cant able to reopen this pull request

**Comment by darkRaspberry** [comment]
you are the author so you can always open

**Comment by AkhilGKrishnan** [comment]
hello @darkRaspberry 
But i cant reopen this pull request.

**Comment by darkRaspberry** [comment]
I am afraid i can't help with this.
Reopen PR option generally lies in bottom of this conversation.
That's a basic feature. Do you get any error comment here.

If u seriously can't able to reopen this pull request. 
Try creating a new PULL request and full swag form again.

**Comment by AkhilGKrishnan** [comment]
> I am afraid i can't help with this.
> Reopen PR option generally lies in bottom of this conversation.
> That's a basic feature. Do you get any error comment here.
> 
> If u seriously can't able to reopen this pull request.
> Try creating a new PULL request and full swag form again.

Thanks

**Comment by AkhilGKrishnan** [comment]
hey @darkRaspberry ,
could you please check below pull request, please let me know if there any mistake in the pull request,
[](https://github.com/education/graduation/pull/2291)

**Comment by AkhilGKrishnan** [comment]
#2291

**Comment by AkhilGKrishnan** [comment]
> We have reviewed memo your application to the yearbook. It looks great sparkles but we found that your profile picture doesn't have the minimum size. It should be at least 544x544 pixels but it is 378.0x378.0 px. I will close this PR so you can do the changes requested. You can open it again once you've done the fixes and we will review it again.blush

**Add my name to class** #2291

**Comment by AkhilGKrishnan** [comment]
#2291

**Comment by AkhilGKrishnan** [comment]
#2291 ("Add my name to class")

**Comment by AkhilGKrishnan** [comment]
#Add my name to class #2291

**Pull request closed without merging**
