### PR TITLE
Ihtisham's pull request

### PR DESCRIPTION
**Pull request by ihtishamKhan**
# Application to the Class of 2020🎓

This pull request template helps you complete an application to the **Class of 2020**. Use the checklist below to verify you have followed the instructions correctly. 

## Checklist ✅

- [x] I have read the instructions on the README file before submitting my application. 
- [x] I made my submission by creating a folder on the `_data` folder and followed the naming convention mentioned in the instructions (`<username>`), added my profile picture and markdown file.
- [x] I have used the Markdown file template to add my information to the Year Book.
- [x] I have completed the form: `https://airtable.com/shrmuHxu38ZariKJi`
- [x] My application belongs to:
  - [x] **Tier 1** 📖: I added myself to the Year Book.
  - [ ] ~~**Tier 2** ✏️: I wrote a post on DEV about a project I built.~~
  - [ ] ~~**Tier 3** ✨: I want my project to be highlighted on stream.~~
- [x] I understand that a reviewer will merge my pull request after examining it or ask for changes in case needed.
- [x] I understand I should not tag or add a reviewer to this Pull Request.
- [x] I understand the photo added to the template will be used in the ceremony "Graduate Walk". 
- [x] I have [added the event](http://www.google.com/calendar/event?action=TEMPLATE&dates=20200615T160000Z%2F20200615T183000Z&text=%24%20git%20remote%20%3Cgraduation%3E%20%F0%9F%8E%93&location=https%3A%2F%2Fwww.twitch.tv%2Fgithubeducation&details=) to my Calendar.

### CODE REVIEW

**Comment by ihtishamKhan** [comment]
> Image is in wrong dimensions (500x500px). As per the requirement
> 
> > Accepted files are png and jpg, should be squared and minimum size 544x544 pixels

How can I edit it now? Do I have to change it on my on forked repo and again do a pull request? And do I have to fill the form again?

**Comment by ShaunLWM** [comment]
> > Image is in wrong dimensions (500x500px). As per the requirement
> > > Accepted files are png and jpg, should be squared and minimum size 544x544 pixels
> 
> How can I edit it now? Do I have to change it on my on forked repo and again do a pull request? And do I have to fill the form again?

You can just commit all the changes in the fork and update this pull request.  Don't have to create a new pull request.

The form is fine. You don't have to submit it again.

**Comment by ihtishamKhan** [comment]
> > > Image is in wrong dimensions (500x500px). As per the requirement
> > > > Accepted files are png and jpg, should be squared and minimum size 544x544 pixels
> > 
> > 
> > How can I edit it now? Do I have to change it on my on forked repo and again do a pull request? And do I have to fill the form again?
> 
> You can just commit all the changes in the fork and update this pull request. Don't have to create a new pull request.
> 
> The form is fine. You don't have to submit it again.

Hey Shaun, check if everything is right now. I did update the picture in my forked repo

**Comment by ShaunLWM** [comment]
Image still seems to be off.
```https://raw.githubusercontent.com/education/graduation/fc0f9075a10d0d9d389a683a1b09920b297beb36/_data/IhtishamUlHassan/Ihtisham.jpg``` shows 2641x2640px, off by a pixel.

Also, I realized that the directory name is different from your username. In this case, I think it's best to delete the fork and redo it as it may be simpler that way. As per the requirements:

> Fork this repository, create a new folder inside the _data folder, and name it with your username. It should look something like this _data/<YOUR-USERNAME>/.

**Comment by ihtishamKhan** [comment]
> Image still seems to be off.
> `https://raw.githubusercontent.com/education/graduation/fc0f9075a10d0d9d389a683a1b09920b297beb36/_data/IhtishamUlHassan/Ihtisham.jpg` shows 2641x2640px, off by a pixel.
> 
> Also, I realized that the directory name is different from your username. In this case, I think it's best to delete the fork and redo it as it may be simpler that way. As per the requirements:
> 
> > Fork this repository, create a new folder inside the _data folder, and name it with your username. It should look something like this _data//.

okay, I am doing the whole process again

**Pull request closed without merging**
