### PR TITLE
Rizwaan Would Like Clarification

### PR DESCRIPTION
**Pull request by Riz-waan**
Hey @juanpflores Sorry for tagging you but this is in response to my previous pull request where I had asked a question. https://github.com/education/graduation/pull/1382 I would appreciate it if you or someone could clarify for me. Continuing from that comment, I just realized it might seem a bit too argumentative I am sorry. I just felt like I missed something else too as I couldn't find anywhere that said your profile picture must be of yourself as it is more widely accepted that profile pictures can be anything. But I am willing to change my image however I think you really need to clarify that on the readme as the instructions were not clear, but before I do I need to make sure if the following image is alright: 
Rozo

_With this time and age, you know how it can be, people being racially and religiously discriminative and I just felt like that could be a reason for mine profile pic saying God Is Great. It wasn't clear that you wanted a picture of yourself because universally profile pics are accepted to be anything and I just felt like maybe other people had images not of themselves, school crest, or octat. Sorry for the misunderstanding, but you still need to specify on instructions._

Do not merge, I have not edited the image yet. I am waiting for clarification. All in all, I understand your effort and really appreciate it!

# Application to the Class of 2020🎓

*Here is the Checklist from the other one if I can use my already existing image*

This pull request template helps you complete an application to the **Class of 2020**. Use the checklist below to verify you have followed the instructions correctly. 

## Checklist ✅

- [x] I have read the instructions on the README file before submitting my application. 
- [x] I made my submission by creating a folder on the `_data` folder and followed the naming convention mentioned in the instructions (`<username>`), added my profile picture and markdown file.
- [x] I have used the Markdown file template to add my information to the Year Book.
- [x] I have completed the form: `https://airtable.com/shrmuHxu38ZariKJi`
- [x] My application belongs to:
  - [x] **Tier 1** 📖: I added myself to the Year Book.
  - [x] **Tier 2** ✏️: I wrote a post on DEV about a project I built.
  - [x] **Tier 3** ✨: I want my project to be highlighted on stream.
- [x] I understand that a reviewer will merge my pull request after examining it or ask for changes in case needed.
- [x] I understand I should not tag or add a reviewer to this Pull Request.
- [x] I understand the photo added to the template will be used in the ceremony "Graduate Walk". 
- [x] I have [added the event](http://www.google.com/calendar/event?action=TEMPLATE&dates=20200615T160000Z%2F20200615T183000Z&text=%24%20git%20remote%20%3Cgraduation%3E%20%F0%9F%8E%93&location=https%3A%2F%2Fwww.twitch.tv%2Fgithubeducation&details=) to my Calendar.

### CODE REVIEW

**Comment by Riz-waan** [comment]
Wait so @Mohammed-Shoaib Could I continue with my original image? Which is on this Pull Request as I feel like Allahu Akbar represents me, as religion comes before anything else personally. And like you are saying if people use scenery which isn't a picture of themselves, school crest, or octat I feel like it is discriminating.

**Comment by Riz-waan** [comment]
# Application to the Class of 2020🎓

*Here is the Checklist from the other one if I can use my already existing image*

This pull request template helps you complete an application to the **Class of 2020**. Use the checklist below to verify you have followed the instructions correctly. 

## Checklist ✅

- [x] I have read the instructions on the README file before submitting my application. 
- [x] I made my submission by creating a folder on the `_data` folder and followed the naming convention mentioned in the instructions (`<username>`), added my profile picture and markdown file.
- [x] I have used the Markdown file template to add my information to the Year Book.
- [x] I have completed the form: `https://airtable.com/shrmuHxu38ZariKJi`
- [x] My application belongs to:
  - [x] **Tier 1** 📖: I added myself to the Year Book.
  - [x] **Tier 2** ✏️: I wrote a post on DEV about a project I built.
  - [x] **Tier 3** ✨: I want my project to be highlighted on stream.
- [x] I understand that a reviewer will merge my pull request after examining it or ask for changes in case needed.
- [x] I understand I should not tag or add a reviewer to this Pull Request.
- [x] I understand the photo added to the template will be used in the ceremony "Graduate Walk". 
- [x] I have [added the event](http://www.google.com/calendar/event?action=TEMPLATE&dates=20200615T160000Z%2F20200615T183000Z&text=%24%20git%20remote%20%3Cgraduation%3E%20%F0%9F%8E%93&location=https%3A%2F%2Fwww.twitch.tv%2Fgithubeducation&details=) to my Calendar.

**Comment by juanpflores** [comment]
This image is 👍

**Comment by Riz-waan** [comment]
@juanpflores Done I changed the image. I would still like to know why my original image was disallowed where other people's pictures not fitting your clear criteria in the other comment was allowed. I know you probably don't have time to explain it to me so no hurry, but I would still like to be enlightened.

**Comment by Abhishekds94** [comment]
> @juanpflores Done I changed the image. I would still like to know why my original image was disallowed where other people's pictures not fitting your clear criteria in the other comment was allowed. I know you probably don't have time to explain it to me so no hurry, but I would still like to be enlightened.

No offense and nothing personal here but, one of the mentioned criteria is not to tag any of the moderator or the owner in your PRs. I hope it is clear. 
If there is a rejection with a reason mentioned, kindly update your PR instead of asking for reasons on this public platform. I hope this makes sense.

Thanks!

**Comment by Riz-waan** [comment]
Oh completely sorry, that was my fault! I must have misread. I only knew I shouldn't assign a reviewer. Where can I ask for reasons? At first, I felt being personally attacked because I was told that the instructions were clear and I still have yet to find those instructions. I just wanted to make sure that the instructions were clear as they were not since other reviewers will accept my image. I completely understand, is there a private way to ask for reasons? 

Also sorry again for tagging, completely my fault.

Thanks soo much for your understanding.

**Comment by Riz-waan** [comment]
Thanks and sorry again, that was my mistake. I must have overlooked it.

**Comment by mitulsavani** [comment]
I have been overlooking this and the previous PR of the contributor! Appreciate you guys @Abhishekds94 @Mohammed-Shoaib for jumping in and clarifying the queries for the most part, good job 👍

**Pull request merged**
