### PR TITLE
Yayy

### PR DESCRIPTION
**Pull request by CrRak**
# Application to the Class of 2020🎓

This pull request template helps you complete an application to the **Class of 2020**. Use the checklist below to verify you have followed the instructions correctly. 

## Checklist ✅

- [x] I have read the instructions on the README file before submitting my application. 
- [x] I made my submission by creating a folder on the `_data` folder and followed the naming convention mentioned in the instructions (`<username>`), added my profile picture and markdown file.
- [x] I have used the Markdown file template to add my information to the Year Book.
- [x] I understand that a reviewer will merge my pull request after examining it or ask for changes in case needed.
- [x] I understand I should not tag or add a reviewer to this Pull Request.
- [x] I understand the photo added to the template will be used in the ceremony "Graduate Walk". 
- [x] I have [added the event](http://www.google.com/calendar/event?action=TEMPLATE&dates=20200615T160000Z%2F20200615T183000Z&text=%24%20git%20remote%20%3Cgraduation%3E%20%F0%9F%8E%93&location=https%3A%2F%2Fwww.twitch.tv%2Fgithubeducation&details=) to my Calendar.

### CODE REVIEW

**Comment by CrRak** [comment]
Which form?

**Comment by Mohammed-Shoaib** [comment]
@CrRak Apologies but your first PR was submitted _after_ the deadline (May 26th, 2020 at 12:00 AM PDT) for the swags. :package: Due to this, you couldn't fill the form as the applications were closed by then. :disappointed:

**Comment by CrRak** [comment]
Please see if anything could be done :(

**Comment by Mohammed-Shoaib** [comment]
@CrRak I don't think so, I am sorry. :cry: They were already out of swags but extended the deadline based on requests from May 23rd to May 26th as they promised May 26th. So I don't think anything can be done now. :disappointed:

**Comment by CrRak** [comment]
Please please please :( :( :(

**Comment by Mohammed-Shoaib** [comment]
@CrRak I am a student volunteer so nothing is in my hands. :frowning_face: But I also feel you need to understand from their perspective. :grimacing: There are a ton of other students who also submitted the form after the deadline and it would be unfair to them. Besides, the education team is well over their limit for swags too.

I hope you can understand and will not let this disappoint you! :disappointed_relieved: We are very happy to have you be part of the yearbook. :blush:

**Pull request merged**
