### PR TITLE
Create aarohi shukla

### PR DESCRIPTION
**Pull request by Aarohi-Shukla**
# Application to the Class of 2020🎓

This pull request template helps you complete an application to the **Class of 2020**. Use the checklist below to verify you have followed the instructions correctly. 

## Checklist ✅

- [ ] I have read the instructions on the README file before submitting my application. 
- [ ] I made my submission by creating a folder on the `_data` folder and followed the naming convention mentioned in the instructions (`<username>`), added my profile picture and markdown file.
- [ ] I have used the Markdown file template to add my information to the Year Book.
- [ ] I have completed the form: `https://airtable.com/shrmuHxu38ZariKJi`
- [ ] My application belongs to:
  - [ ] **Tier 1** 📖: I added myself to the Year Book.
  - [ ] **Tier 2** ✏️: I wrote a post on DEV about a project I built.
  - [ ] **Tier 3** ✨: I want my project to be highlighted on stream.
- [ ] I understand that a reviewer will merge my pull request after examining it or ask for changes in case needed.
- [ ] I understand I should not tag or add a reviewer to this Pull Request.
- [ ] I understand the photo added to the template will be used in the ceremony "Graduate Walk". 
- [ ] I have [added the event](http://www.google.com/calendar/event?action=TEMPLATE&dates=20200615T160000Z%2F20200615T183000Z&text=%24%20git%20remote%20%3Cgraduation%3E%20%F0%9F%8E%93&location=https%3A%2F%2Fwww.twitch.tv%2Fgithubeducation&details=) to my Calendar.

### CODE REVIEW

**Review by darkRaspberry — CHANGES_REQUESTED** [review]
Update your checklist so it's easy to review.

Your checklist are incorrect. Edit ur changes. AND don't add ticks.

Just add the "x" (small x) between [] ( square bracket)
like this `[x]` not this [ x] or [x ] or [ ] x

only Correct way `[x]`

**Review by juanpflores — COMMENTED** [review]
We were not able to find your form submission on our side. Fill a shipping form before we can move on with your revew.

**Review by juanpflores — COMMENTED** [review]
We were not able to find your form submission on our side. Fill a shipping form before we can move on with your revew.

**Comment by elisemoe** [comment]
Hi @Aarohi-Shukla 👋😄 we can't wait to celebrate graduation with you! Be sure to submit the form before 12:00 AM PT today (in ~2.5hr) to be considered for swag.

**Review by Mohammed-Shoaib — CHANGES_REQUESTED** [review]
Hey @Aarohi-Shukla,

Congrats on graduating! :mortar_board: :tada:

You haven't added your information! :no_good: Please add the following 2 files:
1. A markdown file
2. A profile image

Please read instructions on the [README](https://github.com/education/graduation/blob/master/README.md) file for more information.

Also as mentioned by @darkRaspberry, the checklist hasn't been marked. We _cannot_ add your information to the yearbook without your permission. You can edit your [comment](https://github.com/education/graduation/pull/565#issue-420594819) and mark the task list by changing `[ ]` to `[x]`. Please refer [here](https://help.github.com/en/github/managing-your-work-on-github/about-task-lists) for more information.

Could you please make these changes? :memo:

Thanks,
Mohammed Shoaib

**Review by juanpflores — CHANGES_REQUESTED** [review]
We have reviewed 📝 your application to the yearbook. It looks great ✨ but we found that You are modifying 1 files while you should only modify 2 (one image and one md file). I will close this PR so you can do the changes requested. You can open a new one once you've done the fixes and we will review it again.😊

**Pull request closed without merging**
