### PR TITLE
To submit pull request

### PR DESCRIPTION
**Pull request by rohitashkmwt**
# Application to the Class of 2020🎓

This pull request template helps you complete an application to the **Class of 2020**. Use the checklist below to verify you have followed the instructions correctly. 

## Checklist ✅

- [x] I have read the instructions on the README file before submitting my application. 
- [x] I made my submission by creating a folder on the `_data` folder and followed the naming convention mentioned in the instructions (`<username>`), added my profile picture and markdown file.
- [x] I have used the Markdown file template to add my information to the Year Book.
- [x] I have completed the form: `https://airtable.com/shrmuHxu38ZariKJi`
- [x] My application belongs to:
  - [x] **Tier 1** 📖: I added myself to the Year Book.
  - [x] **Tier 2** ✏️: I wrote a post on DEV about a project I built.
  - [x] **Tier 3** ✨: I want my project to be highlighted on stream.
- [x] I understand that a reviewer will merge my pull request after examining it or ask for changes in case needed.
- [x] I understand I should not tag or add a reviewer to this Pull Request.
- [x] I understand the photo added to the template will be used in the ceremony "Graduate Walk". 
- [x] I have [added the event](http://www.google.com/calendar/event?action=TEMPLATE&dates=20200615T160000Z%2F20200615T183000Z&text=%24%20git%20remote%20%3Cgraduation%3E%20%F0%9F%8E%93&location=https%3A%2F%2Fwww.twitch.tv%2Fgithubeducation&details=) to my Calendar.

### CODE REVIEW

**Comment by rohitashkmwt** [comment]
rohitashkmwt

**Comment by rohitashkmwt** [comment]
Profile added.

**Comment by rohitashkmwt** [comment]
> We have reviewed 📝 your application to the yearbook. It looks great ✨ but we found that You are modifying 1 files while you should only modify 2 (one image and one md file). I will close this PR so you can do the changes requested. You can open a new one once you've done the fixes and we will review it again.😊

I alredy modified so I don't want to further modify these files so you can merge this pull request😊.

**Comment by CLiu13** [comment]
You need to add the image to your folder via a commit (posting it in a comment doesn't work unfortunately) - otherwise, the PR cannot be merged. Please feel free to re-open this PR with the changes, or to open a new one.

**Comment by CLiu13** [comment]
Thanks for the picture - however, you need to add it to your folder by adding another commit to this PR, rather than leaving a comment here. You can do this by moving the image file to the folder on your local computer, and then creating a new commit on your branch.

**Comment by rohitashkmwt** [comment]
> You need to add the image to your folder via a commit (posting it in a comment doesn't work unfortunately) - otherwise, the PR cannot be merged. Please feel free to re-open this PR with the changes, or to open a new one.

rohitashkmwt

**Comment by rohitashkmwt** [comment]
Please reopen this pull request.

**Comment by juanpflores** [comment]
Unfortunately, I don't have the ability to reopen it

**Comment by rohitashkmwt** [comment]
> Unfortunately, I don't have the ability to reopen it

Please let me know how to reopen this or should I create new PR referencing this.

**Comment by Abhishekds94** [comment]
> > Unfortunately, I don't have the ability to reopen it
> 
> Please let me know how to reopen this or should I create new PR referencing this.

Create a new PR with the updated files and leave a link to the PR here, just in case!

**Comment by rohitashkmwt** [comment]
> > > Unfortunately, I don't have the ability to reopen it
> > 
> > 
> > Please let me know how to reopen this or should I create new PR referencing this.
> 
> Create a new PR with the updated files and leave a link to the PR here, just in case!

Please tell me another way to add picture to the repository because at this time I'm unable to create  new PR.

**Comment by rohitashkmwt** [comment]
> > > Unfortunately, I don't have the ability to reopen it
> > 
> > 
> > Please let me know how to reopen this or should I create new PR referencing this.
> 
> Create a new PR with the updated files and leave a link to the PR here, just in case!



> Thanks for the picture - however, you need to add it to your folder by adding another commit to this PR, rather than leaving a comment here. You can do this by moving the image file to the folder on your local computer, and then pushing a new commit to your branch.

I've created new PR so please have look and let me know

**Pull request closed without merging**
