### PR TITLE
Made changes as requested

### PR DESCRIPTION
**Pull request by Akshay-kumarA**
# Application to the Class of 2020🎓

This pull request template helps you complete an application to the **Class of 2020**. Use the checklist below to verify you have followed the instructions correctly. 

## Checklist ✅

- [x] I have read the instructions on the README file before submitting my application. 
- [x] I made my submission by creating a folder on the `_data` folder and followed the naming convention mentioned in the instructions (`<username>`), added my profile picture and markdown file.
- [x] I have used the Markdown file template to add my information to the Year Book.
- [x] I have completed the form: `https://airtable.com/shrmuHxu38ZariKJi`
- [x] My application belongs to:
  - [x] **Tier 1** 📖: I added myself to the Year Book.
  - [x] **Tier 2** ✏️: I wrote a post on DEV about a project I built.
  - [x] **Tier 3** ✨: I want my project to be highlighted on stream.
- [x] I understand that a reviewer will merge my pull request after examining it or ask for changes in case needed.
- [x] I understand I should not tag or add a reviewer to this Pull Request.
- [x] I understand the photo added to the template will be used in the ceremony "Graduate Walk". 
- [x] I have [added the event](http://www.google.com/calendar/event?action=TEMPLATE&dates=20200615T160000Z%2F20200615T183000Z&text=%24%20git%20remote%20%3Cgraduation%3E%20%F0%9F%8E%93&location=https%3A%2F%2Fwww.twitch.tv%2Fgithubeducation&details=) to my Calendar.

### CODE REVIEW

**Comment by Akshay-kumarA** [comment]
> File uploaded has different name as compared to the one in the markdown file. Markdown `akshay.jpg` vs uploaded `akshaykumarA,jpg`. Please change either one of them to match the other.

i made changes please review it

**Comment by Akshay-kumarA** [comment]
> name of photo should be same the above mentioned in md file

Changed name

**Comment by ShaunLWM** [comment]
I realized your folder and markdown file differs from your username as well. As per the requirements,

> Fork this repository, create a new folder inside the _data folder, and name it with your username. It should look something like this _data/<YOUR-USERNAME>

> Create a markdown file in your folder following the convention <YOUR-USERNAME>.md

**Comment by ShaunLWM** [comment]
Delete the unneeded folder as well. There should only be 2 changes to the commit. Thank you!

**Comment by Akshay-kumarA** [comment]
> Delete the unneeded folder and files as well. There should only be 2 changes to the commit. Thank you! Currently 4.

Deleted old files

**Pull request closed without merging**
