### PR TITLE
added graduation information

### PR DESCRIPTION
**Pull request by anebz**
# Application to the Class of 2020🎓

This pull request template helps you complete an application to the **Class of 2020**. Use the checklist below to verify you have followed the instructions correctly. 

## Checklist ✅

- [X] I have read the instructions on the README file before submitting my application. 
- [X] I made my submission by creating a folder on the `_data` folder and followed the naming convention mentioned in the instructions (`<username>`), added my profile picture and markdown file.
- [X] I have used the Markdown file template to add my information to the Year Book.
- [X] I have completed the form: `https://airtable.com/shrmuHxu38ZariKJi`
- [X] My application belongs to:
  - [X] **Tier 1** 📖: I added myself to the Year Book.
  - [X] **Tier 2** ✏️: I wrote a post on DEV about a project I built.
  - [X] **Tier 3** ✨: I want my project to be highlighted on stream.
- [X] I understand that a reviewer will merge my pull request after examining it or ask for changes in case needed.
- [X] I understand I should not tag or add a reviewer to this Pull Request.
- [X] I understand the photo added to the template will be used in the ceremony "Graduate Walk". 
- [X] I have [added the event](http://www.google.com/calendar/event?action=TEMPLATE&dates=20200615T160000Z%2F20200615T183000Z&text=%24%20git%20remote%20%3Cgraduation%3E%20%F0%9F%8E%93&location=https%3A%2F%2Fwww.twitch.tv%2Fgithubeducation&details=) to my Calendar.

### CODE REVIEW

**Comment by elisemoe** [comment]
Hello 👋😄 we can't wait to celebrate graduation with you! Be sure to submit the form before 12:00 AM PT today (in ~2.5hr) to be considered for swag. Your PR does not need to be merged before midnight.

**Comment by anebz** [comment]
Apologies, it took me longer than I thought to write the dev post. I did the form already. Thank you!

**Comment by anebz** [comment]
> 
> 
> Hey @anebz,
> 
> Congrats on graduating! 🎓 🎉 Thanks for filling out the form!
> 
> Unfortunately, the image is not squared (1:1 or width = height) 🔳 The size of the image is 318x324 (pixels). Please also do keep in mind the size of the image must be **at least** 544x544 (pixels).
> 
> Could you please make this change? 📝
> 
> Thanks,
> Mohammed Shoaib

done! thanks

**Comment by anebz** [comment]
Hi @Mohammed-Shoaib does that mean the pull can be merged? Because it says here it's blocked. Thanks

**Comment by Mohammed-Shoaib** [comment]
Hey @anebz,

Your pull request is perfect! :confetti_ball: I approved the changes. :+1:

However, I cannot merge it as I do not have write access. You'll have to wait for a reviewer with _write_ access to merge your pull request.

Till then sit back, relax, and enjoy :relaxed: 

Best,
Mohammed Shoaib

**Pull request merged**
