### PR TITLE
Adds nizarmah

### PR DESCRIPTION
**Pull request by nizarmah**
# Application to the Class of 2020🎓

This pull request template helps you complete an application to the **Class of 2020**. Use the checklist below to verify you have followed the instructions correctly. 

## Checklist ✅

- [x] I have read the instructions on the README file before submitting my application. 
- [x] I made my submission by creating a folder on the `_data` folder and followed the naming convention mentioned in the instructions (`<username>`), added my profile picture and markdown file.
- [x] I have used the Markdown file template to add my information to the Year Book.
- [x] I have completed the form: `https://airtable.com/shrmuHxu38ZariKJi`
- [x] My application belongs to:
  - [x] **Tier 1** 📖: I added myself to the Year Book.
  - [x] **Tier 2** ✏️: I wrote a post on DEV about a project I built.
  - [x] **Tier 3** ✨: I want my project to be highlighted on stream.
- [x] I understand that a reviewer will merge my pull request after examining it or ask for changes in case needed.
- [x] I understand I should not tag or add a reviewer to this Pull Request.
- [x] I understand the photo added to the template will be used in the ceremony "Graduate Walk". 
- [x] I have [added the event](http://www.google.com/calendar/event?action=TEMPLATE&dates=20200615T160000Z%2F20200615T183000Z&text=%24%20git%20remote%20%3Cgraduation%3E%20%F0%9F%8E%93&location=https%3A%2F%2Fwww.twitch.tv%2Fgithubeducation&details=) to my Calendar.

### CODE REVIEW

**Comment by nizarmah** [comment]
Pull request is still a draft / work in progress because I am finishing my DEV post. Once I publish my DEV post, I'll remove the pull request from draft. In addition, I'll submit the form for the *swag*.

**Comment by nizarmah** [comment]
[DEV Post is posted now](https://dev.to/nizarmah_/building-an-open-source-face-recognition-android-app-stage-1-1mk7). Ready to be merged.

**Comment by nizarmah** [comment]
I'm glad, if there's anything I can help with, such as going through the available pull requests and giving them certain labels if:
* the image is under the necessary dimensions
* if the strings exceed the maximum length of characters
* if the image name doesn't match the image file

Please, let me know. I have a bit of free time on my hands lately and I'd be more than happy to help!  To be fair, I would be honored to help.

**Comment by elisemoe** [comment]
> I'm glad.
> 
> By the way, if there's anything I can help with, such as going through the available pull requests and giving them certain labels if:
> 
> * the image is under the necessary dimensions
> * if the strings exceed the maximum length of characters
> * if the image name doesn't match the image file
> 
> Please, let me know. I have a bit of free time on my hands lately and I'd be more than happy to help! To be fair, I would be honored to help.

Hi @nizarmah ! That is incredibly nice of you :) Juan Pa wrote up a few things we'd love help with here: https://github.com/education/graduation/issues/805#issuecomment-632758736

You're also welcome to help anyone with questions they've asked in their pull requests.

**Comment by nizarmah** [comment]
Thank you so much! In a couple of hours it'll be morning in my timezone and then I'll definitely check how I can help exactly. Have a wonderful day. And thank you both for your hard work and this opportunity (:

**Pull request merged**
