### PR TITLE
Kamal

### PR DESCRIPTION
**Pull request by ikamalrawal**
# Application to the Class of 2020🎓

This pull request template helps you complete an application to the **Class of 2020**. Use the checklist below to verify you have followed the instructions correctly. 

## Checklist ✅

- [x] I have read the instructions on the README file before submitting my application. 
- [x] I made my submission by creating a folder on the `_data` folder and followed the naming convention mentioned in the instructions (`<username>`), added my profile picture and markdown file.
- [x] I have used the Markdown file template to add my information to the Year Book.
- [x] I have completed the form: `https://airtable.com/shrmuHxu38ZariKJi`
- [x] My application belongs to:
  - [x] **Tier 1** 📖: I added myself to the Year Book.
  - [ ] **Tier 2** ✏️: I wrote a post on DEV about a project I built.
  - [ ] **Tier 3** ✨: I want my project to be highlighted on stream.
- [x] I understand that a reviewer will merge my pull request after examining it or ask for changes in case needed.
- [x] I understand I should not tag or add a reviewer to this Pull Request.
- [x] I understand the photo added to the template will be used in the ceremony "Graduate Walk". 
- [x] I have [added the event](http://www.google.com/calendar/event?action=TEMPLATE&dates=20200615T160000Z%2F20200615T183000Z&text=%24%20git%20remote%20%3Cgraduation%3E%20%F0%9F%8E%93&location=https%3A%2F%2Fwww.twitch.tv%2Fgithubeducation&details=) to my Calendar.

### CODE REVIEW

**Comment by ikamalrawal** [comment]
> Update your checklist so it's easy to review.
> 
> Your checklist are incorrect. Edit ur changes. AND don't add ticks.
> 
> Just add the "x" (small x) between [] ( square bracket)
> like this `[x]` not this [ x] or [x ] or [ ] x
> 
> only Correct way `[x]`

Done :)

**Comment by darkRaspberry** [comment]
Still u not corrected.
Put No space between `[x]` this.
This is not correct `[ x ]`

**Comment by ikamalrawal** [comment]
> Still u not corrected.
> Put No space between `[x]` this.
> This is not correct `[ x ]`

Is it fine now?   
when i put [x] it automatically changed to tick mark after updating.

**Comment by darkRaspberry** [comment]
Now it's good. Wait for merge

**Comment by ikamalrawal** [comment]
Hello,  I am not able to understand what changes i have to do

**Comment by ikamalrawal** [comment]
How to open the pull request again ?

**Comment by darkRaspberry** [comment]
Click on reopen in this pull request.
After the required chnges,

**Comment by ikamalrawal** [comment]
> Click on reopen in this pull request.
> After the required chnges,

Not getting an option of Reopen

**Comment by ikamalrawal** [comment]
I have created another pull request #2436

**Pull request closed without merging**
