### PR TITLE
Add Entry to Yearbook

### PR DESCRIPTION
**Pull request by vansjyo**
# Application to the Class of 2020🎓

This pull request template helps you complete an application to the **Class of 2020**. Use the checklist below to verify you have followed the instructions correctly. 

## Checklist ✅

- [x] I have read the instructions on the README file before submitting my application. 
- [x] I made my submission by creating a folder on the `_data` folder and followed the naming convention mentioned in the instructions (`vanjyo`), added my profile picture and markdown file.
- [x] I have used the Markdown file template to add my information to the Year Book.
- [x] I have completed the form: `https://airtable.com/shrmuHxu38ZariKJi`
- [x] My application belongs to:
  - [x] **Tier 1** 📖: I added myself to the Year Book.
  - [ ] **Tier 2** ✏️: I wrote a post on DEV about a project I built.
  - [ ] **Tier 3** ✨: I want my project to be highlighted on stream.
- [x] I understand that a reviewer will merge my pull request after examining it or ask for changes in case needed.
- [x] I understand I should not tag or add a reviewer to this Pull Request.
- [x] I understand the photo added to the template will be used in the ceremony "Graduate Walk". 
- [x] I have [added the event](http://www.google.com/calendar/event?action=TEMPLATE&dates=20200615T160000Z%2F20200615T183000Z&text=%24%20git%20remote%20%3Cgraduation%3E%20%F0%9F%8E%93&location=https%3A%2F%2Fwww.twitch.tv%2Fgithubeducation&details=) to my Calendar.

### CODE REVIEW

**Comment by vansjyo** [comment]
Updated

**Comment by y-martinez** [comment]
Hi! @vansjyo  this is not valid PR because it does not follow the structure of the PR template, it is no longer valid because the new PR does not apply to any Tier, please check the updates in the readme file.

Update the PR with the new template PR.

**Comment by vansjyo** [comment]
I guess there is some problem with the PR, the `vansjyo` folder got added to the root directory instead `_data` folder.

**Comment by y-martinez** [comment]
Hi! @vansjyo two things, 
Why didn't you change the template format? I informed you that it was not the updated one.

I was reviewing your commits, and the folder is not in `_data` because you didn't put it there, remember that PR is the union of what you did (your contribution to a project) with the code.

**Comment by vansjyo** [comment]
Yes, I apologize for that and I understood that mistake was mine. My previous PR was inside the `_data` folder itself. I committed an error in the new PR. I have sent a PR to revert the changes. Apologies again.

**Pull request merged**
