### PR TITLE
Adding graduation profile

### PR DESCRIPTION
**Pull request by dyasem**
# Application to the Class of 2020🎓

This pull request template helps you complete an application to the **Class of 2020**. Use the checklist below to verify you have followed the instructions correctly. 

## Checklist ✅

- [x] I have read the instructions on the README file before submitting my application. 
- [x] I made my submission by creating a folder on the `_data` folder and followed the naming convention mentioned in the instructions (`<username>`), added my profile picture and markdown file.
- [x] I have used the Markdown file template to add my information to the Year Book.
- [x] I have completed the form: `https://airtable.com/shrmuHxu38ZariKJi`
- [x] My application belongs to:
  - [x] **Tier 1** 📖: I added myself to the Year Book.
  - [x] **Tier 2** ✏️: I wrote a post on DEV about a project I built.
  - [x] **Tier 3** ✨: I want my project to be highlighted on stream.
- [x] I understand that a reviewer will merge my pull request after examining it or ask for changes in case needed.
- [x] I understand I should not tag or add a reviewer to this Pull Request.
- [x] I understand the photo added to the template will be used in the ceremony "Graduate Walk". 
- [x] I have [added the event](http://www.google.com/calendar/event?action=TEMPLATE&dates=20200615T160000Z%2F20200615T183000Z&text=%24%20git%20remote%20%3Cgraduation%3E%20%F0%9F%8E%93&location=https%3A%2F%2Fwww.twitch.tv%2Fgithubeducation&details=) to my Calendar.

### CODE REVIEW

**Comment by dyasem** [comment]
@wrik003  Thanks for the corrections.

I have effected the changes.

**Comment by dyasem** [comment]
@wrik003 Thank you.

I look forward to seeing it being merged.

Also did you mean I could help review PRs?

**Comment by wrik003** [comment]
> Also did you mean I could help review PRs? I will be happy to help.

Yes! Do it the way I did in your case by browsing to the candidate's master branch and checking if both the files exist and they follow the rules.

**Comment by dyasem** [comment]
Oh great! Thank you man. I've reviewed a couple of them. I will do more!

**Comment by dyasem** [comment]
@wrik003 Please have you merged mine yet?

**Comment by wrik003** [comment]
@dyasem I don't have merging rights. Don't worry, @juanpflores and team will get it done.

**Comment by dyasem** [comment]
@wrik003 Oh alright. Thanks man.

**Comment by dyasem** [comment]
@juanpflores Thanks for the heads up, but please I did actually filled and submit the shipping form. I did that yesterday.

I can do it a second time if you request that?

**Comment by dyasem** [comment]
@juanpflores Please I have refilled and submitted the form 10hrs ago.

I hope my PR iss merged. Thanks

**Comment by dyasem** [comment]
@elisemoe Thank you! Can't wait for the graduation event and the swag!

**Pull request merged**
