### PR TITLE
Update BetaPundit details (as per the review in PR #384)

### PR DESCRIPTION
**Pull request by BetaPundit**
# Application to the Class of 2020🎓

This pull request template helps you complete an application to the **Class of 2020**. Use the checklist below to verify you have followed the instructions correctly. 

## Checklist ✅

- [x] I have read the instructions on the README file before submitting my application. 
- [x] I made my submission by creating a folder on the `_data` folder and followed the naming convention mentioned in the instructions (`<username>`), added my profile picture and markdown file.
- [x] I have used the Markdown file template to add my information to the Year Book.
- [x] I have completed the form: `https://airtable.com/shrmuHxu38ZariKJi`
- [x] My application belongs to:
  - [x] **Tier 1** 📖: I added myself to the Year Book.
  - [x] **Tier 2** ✏️: I wrote a post on DEV about a project I built.
  - [x] **Tier 3** ✨: I want my project to be highlighted on stream.
- [x] I understand that a reviewer will merge my pull request after examining it or ask for changes in case needed.
- [x] I understand I should not tag or add a reviewer to this Pull Request.
- [x] I understand the photo added to the template will be used in the ceremony "Graduate Walk". 
- [x] I have [added the event](http://www.google.com/calendar/event?action=TEMPLATE&dates=20200615T160000Z%2F20200615T183000Z&text=%24%20git%20remote%20%3Cgraduation%3E%20%F0%9F%8E%93&location=https%3A%2F%2Fwww.twitch.tv%2Fgithubeducation&details=) to my Calendar.

### CODE REVIEW

**Comment by BetaPundit** [comment]
Okay, so I just read that I need to re-open my previous PR to make changes!
I am a bit unsure about how to do that! 
Some guidance would be appreciated!

**Comment by akhilaku** [comment]
> Okay, so I just read that I need to re-open my previous PR to make changes!
> I am a bit unsure about how to do that!
> Some guidance would be appreciated!

This pull request is fine. If you have filled the "pull request link" in the swag shipment form with this link, then it is enough. You can close the other pull requests.

**Comment by BetaPundit** [comment]
My swag shipment form contains the link to my older PR. (#384 )

**Comment by akhilaku** [comment]
If your old pull request is correct then no worries.

**Comment by BetaPundit** [comment]
I was asked to do some changes in the old PR, and which I did by submitting this new PR!

**Comment by akhilaku** [comment]
If you have that old pull request with you, then you can edit it correctly
and you can send me the link for review and approval.

**Comment by BetaPundit** [comment]
> If you have that old pull request with you, then you can edit it correctly and you can send me the link for review and approval.

Well, that's what I needed help with in the first place! 😅 
#384 this is my old PR.

I am unsure how to edit the same PR!! I tried Googling the solutions but couldn't find any!
Would love to get some help.

**Comment by akhilaku** [comment]
No any issues, you can fill the form with new pull request link.
I can't do anything without the link. I'm doing volunteering work.

**Pull request merged**
